In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt


def split_scalar(indep_X,dep_Y):
    X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
    #X_train, X_test, y_train, y_test = train_test_split(indep_X,dep_Y, test_size = 0.25, random_state = 0)
    
    #Feature Scaling
    #from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    return X_train, X_test, y_train, y_test
    
def r2_prediction(regressor,X_test,y_test):
    y_pred = regressor.predict(X_test)
    from sklearn.metrics import r2_score
    r2=r2_score(y_test,y_pred)
    return r2

def Linear(X_train,y_train,X_test,y_test_original):
    # Fitting K-NN to the Training set
    from sklearn.linear_model import LinearRegression
    regressor = LinearRegression()
    regressor.fit(X_train, y_train)
    r2=r2_prediction(regressor,X_test,y_test_original)
    return r2
    
def svm_linear(X_train,y_train,X_test,y_test_original):
    from sklearn.svm import SVR
    regressor = SVR(kernel = 'linear')
    regressor.fit(X_train, y_train)
    r2=r2_prediction(regressor,X_test,y_test_original)
    return r2
    
def svm_NL(X_train,y_train,X_test,y_test_original):
    from sklearn.svm import SVR
    regressor = SVR(kernel = 'rbf')
    regressor.fit(X_train, y_train)
    r2=r2_prediction(regressor,X_test,y_test_original)
    return r2
    

def Decision(X_train,y_train,X_test,y_test_original):
    # Fitting K-NN to the Training setC
    from sklearn.tree import DecisionTreeRegressor
    regressor = DecisionTreeRegressor(random_state = 0)
    regressor.fit(X_train, y_train)
    r2=r2_prediction(regressor,X_test,y_test_original)
    return r2
    

def random(X_train,y_train,X_test,y_test_original):
    # Fitting K-NN to the Training set
    from sklearn.ensemble import RandomForestRegressor
    regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
    regressor.fit(X_train, y_train)
    r2=r2_prediction(regressor,X_test,y_test_original)
    return r2
    
def rfeFeature(indep_X,dep_Y,n):
    rfelist=[]
    
    from sklearn.linear_model import LinearRegression
    lin = LinearRegression()
    
    from sklearn.svm import SVR
    SVRl = SVR(kernel = 'linear')
    
    from sklearn.svm import SVR
    #SVRnl = SVR(kernel = 'rbf')
    
    from sklearn.tree import DecisionTreeRegressor
    dec = DecisionTreeRegressor(random_state = 0)
    
    from sklearn.ensemble import RandomForestRegressor
    rf = RandomForestRegressor(n_estimators = 10, random_state = 0)
    
    
    rfemodellist=[lin,SVRl,dec,rf]
    for i in rfemodellist:
        print(i)
        log_rfe = RFE(estimator=i, n_features_to_select=n) #Corrected RFE call
        log_fit = log_rfe.fit(indep_X, dep_Y)
        featurename = log_fit.get_support(indices=True) 
        selected_features = df2.columns[featurename]
        features = selected_features.to_list()
        print(f"the best{n} features are",features)
        log_rfe_feature=log_fit.transform(indep_X)
        rfelist.append(log_rfe_feature)
    return rfelist
    
def rfe_regression(acclog,accsvml,accdes,accrf):
    rfedataframe=pd.DataFrame(index=['Linear','SVC','Random','DecisionTree'],columns=['Linear','SVMl', 'Decision','Random'])
    for number,idex in enumerate(rfedataframe.index):
        rfedataframe.loc[idex, 'Linear'] = acclog[number]
        rfedataframe.loc[idex, 'SVMl'] = accsvml[number]
        rfedataframe.loc[idex, 'Decision'] = accdes[number]
        rfedataframe.loc[idex, 'Random'] = accrf[number]
    return rfedataframe



In [2]:
dataset1=pd.read_csv("prep.csv",index_col=None)
df2=dataset1
df2 = pd.get_dummies(df2, drop_first=True)

indep_X=df2.drop('classification_yes', axis=1)
dep_Y=df2['classification_yes']


In [3]:
df2

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...      False        False       False   
1    137.528754  4.627244  10.700000  ...       True        False       False   
2    138.000000  4.400000  12.000000  ...       True        False       False   
3    138.000000  3.200000   8.100000  ...       True        False       False   
4    137.528754  4.627244  11.800000  ...       True        False       False   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...       True        False       False   
395  137.528754  4.627244   8.700000  ...       True        False       False   
396  134.000000  2.700000   9.100000  ...       True        False       False   
397  142.000000  5.500000   8.500000  ...       True        False       False   
398  140.000000  5.000000  16.300000  ...       True        False       False   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0      False   False    False       True    True    False                True  
1      False   False    False       True   False    False                True  
2      False   False    False       True   False    False                True  
3      False   False    False       True   False     True                True  
4      False   False    False       True   False    False                True  
..       ...     ...      ...        ...     ...      ...                 ...  
394    False   False    False       True   False    False                True  
395     True    True    False       True   False     True                True  
396     True    True    False      False   False    False                True  
397     True    True    False       True   False     True                True  
398    False   False    False       True   False    False               False  

[399 rows x 28 columns]

In [4]:
rfelist=rfeFeature(indep_X,dep_Y,3)

acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

LinearRegression()
the best3 features are ['sg_c', 'sg_d', 'sg_e']
SVR(kernel='linear')
the best3 features are ['sg_c', 'sg_d', 'sg_e']
DecisionTreeRegressor(random_state=0)
the best3 features are ['hrmo', 'sg_c', 'sg_d']
RandomForestRegressor(n_estimators=10, random_state=0)
the best3 features are ['al', 'hrmo', 'sg_d']


In [5]:
rfelist

[array([[1., 0., 0.],
        [1., 0., 0.],
        [0., 0., 0.],
        ...,
        [1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0.],
        [1., 0., 0.],
        [0., 0., 0.],
        ...,
        [1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[12.51815562,  1.        ,  0.        ],
        [10.7       ,  1.        ,  0.        ],
        [12.        ,  0.        ,  0.        ],
        ...,
        [ 9.1       ,  1.        ,  0.        ],
        [ 8.5       ,  0.        ,  0.        ],
        [16.3       ,  0.        ,  0.        ]]),
 array([[ 3.        , 12.51815562,  0.        ],
        [ 2.        , 10.7       ,  0.        ],
        [ 1.        , 12.        ,  0.        ],
        ...,
        [ 3.        ,  9.1       ,  0.        ],
        [ 0.        ,  8.5       ,  0.        ],
        [ 0.        , 16.3       ,  0.        ]])]

In [9]:
rfelist=rfeFeature(indep_X,dep_Y,5)

acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

LinearRegression()
the best5 features are ['sg_b', 'sg_c', 'sg_d', 'sg_e', 'htn_yes']
SVR(kernel='linear')
the best5 features are ['sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'htn_yes']
DecisionTreeRegressor(random_state=0)
the best5 features are ['bu', 'hrmo', 'rc', 'sg_c', 'sg_d']
RandomForestRegressor(n_estimators=10, random_state=0)
the best5 features are ['al', 'hrmo', 'rc', 'sg_c', 'sg_d']


In [10]:
rfelist

[array([[0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        ...,
        [0., 1., 0., 0., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.]]),
 array([[1., 0., 0., 1., 0.],
        [1., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        ...,
        [1., 0., 0., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 1., 0.]]),
 array([[ 57.48210526,  12.51815562,   4.70559701,   1.        ,
           0.        ],
        [ 22.        ,  10.7       ,   4.70559701,   1.        ,
           0.        ],
        [ 23.        ,  12.        ,   4.70559701,   0.        ,
           0.        ],
        ...,
        [115.        ,   9.1       ,   3.4       ,   1.        ,
           0.        ],
        [ 80.        ,   8.5       ,   4.70559701,   0.        ,
           0.        ],
        [ 49.        ,  16.3       ,   4.9       ,   0.        ,
           0.        ]]),
 array([[ 3.        , 12.51815562,  4.70559701,  1.        , 

In [11]:
for i in rfelist:
    X_train, X_test, y_train, y_test=split_scalar(i,dep_Y)
    r2_lin=Linear(X_train,y_train,X_test,y_test)
    acclin.append(r2_lin)
    
    r2_sl=svm_linear(X_train,y_train,X_test,y_test)
    accsvml.append(r2_sl)
    
    r2_NL=svm_NL(X_train,y_train,X_test,y_test)
    accsvmnl.append(r2_NL)
    
    r2_d=Decision(X_train,y_train,X_test,y_test)
    accdes.append(r2_d)
    
    r2_r=random(X_train,y_train,X_test,y_test)
    accrf.append(r2_r)
    
result=rfe_regression(acclin,accsvml,accdes,accrf)


In [8]:

result
#3

Linear      SVMl  Decision    Random
Linear        0.441961  0.262153  0.441961  0.441816
SVC           0.441961  0.262153  0.441961  0.441816
Random        0.664893  0.609652  0.965961  0.916304
DecisionTree  0.676174  0.670691  0.933504  0.887256

In [12]:
result
#5

Linear      SVMl  Decision    Random
Linear        0.620124  0.457136   0.77924  0.780135
SVC           0.604508  0.456871  0.776474  0.776745
Random        0.674403  0.628206  0.696181  0.815538
DecisionTree  0.686361  0.643365  0.836806  0.845303